# Generated by Django 4.0.5 on 2023-02-26 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='content_list',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='friend_list',
        ),
        migrations.AddField(
            model_name='customuser',
            name='friend_list',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
