# Generated by Django 4.0.5 on 2023-02-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_customuser_content_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_close_friend',
            field=models.BooleanField(default=False),
        ),
    ]
