# Generated by Django 4.0.5 on 2023-02-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_content_is_close_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friend',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
