# Generated by Django 4.0.5 on 2023-02-28 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_customuser_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='friend',
        ),
    ]
